version: '3.8'

services:
  telegram_bot:
    container_name: tg2alist
    build: .
    environment:
      API_ID: "API_ID"  # 替换为你的实际API ID
      API_HASH: "API_HASH"  # 替换为你的实际API Hash
      PHONE_NUMBER: "PHONE_NUMBER"  # 替换为你的电话号码
      BASE_URL: "BASE_URL"  # 替换为你的实际Base URL
      CHAT_IDS_TO_MONITOR: "CHAT_ID_TO_MONITOR"  # 替换为你要监控的Chat ID，可以监控多个chat，用,分割
      USERNAME: "USERNAME"  # 替换为你的用户名
      PASSWORD: "PASSWORD" # 注意特殊字符要转义
      SERVER_PATH: "/local" # alist服务器目录
      ADMIN_USER_ID:: "" # 管理员ID
    stdin_open: true  # once you've logged in, can be commented out 登入后可以注释掉
    tty: true         # ditto 同上
    volumes:
      - .:/app  # 将主机当前目录映射到容器的工作目录
      - /root/docker/alist/local:/root/docker/alist/local  # 将主机的 alist local 目录映射到容器内
    restart: unless-stopped
